### ISSUE TITLE
Tests pass after errors

### ISSUE THREAD

**Issue by bornatow** [lefthandedgoat/canopy#212]
After upgrading canopy from .21 to .31 (still occurs in .32)

Upon Exceptions (both inside canopy and my own) - Canopy displays error correctly, but after printing out error details - it prints "Passed".

In the summary, The test case is counted twice - as passed and as failed. HTML Reported displays and counts these test cases correctly as failed only.

This particular test tried to input something into Username field, but the webpage didn't load.

The same test run on canopy v.21 prints out error only.

    Test: Iteration 5 
    Couldn't find any elements with selector '#UserName', did you mean:
            Runtime Error
    Error:
    can't find element #UserName
    Url: testpage   ReturnUrl=testpage
    Stack:
       at canopy.core.wait@95.Invoke(IWebDriver arg) in C:\projects\canopy\src\canopy\canopy.fs:line 99
       at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
       at canopy.core.wait(Double timeout, FSharpFunc`2 f) in C:\projects\canopy\src\canopy\canopy.fs:line 95
       at canopy.core.op_ComposeLeft[a](a item, String text) in C:\projects\canopy\src\canopy\canopy.fs:line 321
       at Login.login(String environment, String userName) in C:\GIT\Tests\UTILS\Login
    .fs:line 65
       at PerformanceCheck.testHierarchyForLocalParameters@143-3.Invoke(Unit _arg6) in C:\GIT\Tests\TEST CASES\PerformanceCheck.fs:line 145
       at canopy.runner.runtest$cont@93(suite suite, Test test, Unit unitVar) in C:\projects\canopy\src\canopy\runner.fs:line 102
    Passed

**Comment by lefthandedgoat** [comment]
Ok I will look into it! thanks!

**Comment by lefthandedgoat** [comment]
This is now available in canopy 0.9.33
https://www.nuget.org/packages/canopy/
