### ISSUE TITLE
stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by innate01** [lefthandedgoat/canopy#229]
Occasionally I get the stale element reference error. It is random the script works 5 out of 6 times.

Partial call stack below.

Error:
stale element reference: element is not attached to the page document
  (Session info: chrome=47.0.2526.106)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.1 SP1 x86_64)
Url: http://www.reddit.com/Search/
Stack:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.get_Text()
   at canopyExtensions.read[a](a selector) in C:\projects\src\common\canopyExtensions.fs:line 338
   at search.getSearchResults() in C:\projects\src\tests.ui\Tests\search_scenarios.fs:line 96
   at search..smoke@232-806.Invoke(Unit _arg4) in C:\projects\src\tests.ui\Tests\search_scenarios.fs:line 254
   at canopy.runner.runtest$cont@107(suite suite, Test test, Unit unitVar) in C:\projects\canopy\src\canopy\runner.fs:line 115

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.44

Enjoy!
