### ISSUE TITLE
LiveHtmlReporter jQuery error

### ISSUE THREAD

**Issue by Kemyke** [lefthandedgoat/canopy#282]
LiveHtmlReporter crashed with a strange error:

```
Unhandled Exception: System.InvalidOperationException: $ is not defined (UnexpectedJavaScriptError)

2016-08-04T03:05:08.4046160Z    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)

2016-08-04T03:05:08.4056172Z    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

2016-08-04T03:05:08.4066222Z    at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)

2016-08-04T03:05:08.4076188Z    at canopy.reporters.LiveHtmlReporter.saveReportHtml(String directory, String filename) in C:\projects\canopy\src\canopy\reporters.fs:line 242

2016-08-04T03:05:08.4076188Z    at canopy.reporters.LiveHtmlReporter.canopy-reporters-IReporter-quit() in C:\projects\canopy\src\canopy\reporters.fs:line 352
```

It is like the jQuery wasn't loaded. This was a one time error if i run the build again on the server it runs successfully. Do you have any idea what was the problem? Have you ever seen this error message?

**Comment by Kemyke** [comment]
If i am right, the problem is with the exception handling.
The reporter could't load the template but no exception was thrown. The swallowedJS function contains an empty catch block so no error message is logged or shown anywhere.  That is why only the last call throws an exception. (the js function which is called in reportHtml)

Wouldn't it be better to inform the user if the template is not reachable?

**Comment by lefthandedgoat** [comment]
I think that would only be possible if github or the jquery CDN is down, which is rare?

**Comment by Kemyke** [comment]
Yes you are right, i am quite sure that we had some network problems at that time. 

But i think the error handling should be more specific. The empty catch is rarely a good idea. And it is hard to figure out the problem from the exception at the end of the test run.

**Comment by lefthandedgoat** [comment]
I agree that it is generally not a good idea, but the only 'real' way to handle an error loading jquery from a CDN is to log it.  I guess I can update the reporter to log any JS errors.
