### ISSUE TITLE
Running tests in parallel throws IOException

### ISSUE THREAD

**Issue by curdincaspar** [lefthandedgoat/canopy#387]
If I have multiple tests running at the same time I get exceptions because of the "failedContexts.txt" file.
Is there a way to disable this?

>System.IO.IOException: The process cannot access the file 'C:\Users\x\AppData\Roaming\canopy\failedContexts.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at canopy.history.save(FSharpList`1 results) in C:\projects\canopy\src\canopy\history.fs:line 12
   at canopy.runner.run() in C:\projects\canopy\src\canopy\runner.fs:line 235

**Comment by lefthandedgoat** [comment]
In parallel, as in your launch your console app more than ones and run them at the same time?

I will look to see if StreamWriter has the ability to write w/o a hard lock on the file.

**Comment by lefthandedgoat** [comment]
After doing some reading it looks like I don't need to do file create at all and the streamwriter will handle it all.

**Comment by curdincaspar** [comment]
I created multiple AppDomains in order to run the tests in parallel in the same instance of the console app.
This works perfectly except of this "failedContexts.txt".

But what happens if two tests try to write to this file at the same time now?

**Comment by lefthandedgoat** [comment]
Ok.  I will publish a new version with these changes and they *may* help.  The problem is that canopy was never really designed to run in parallel.  

If you don't use the 'RunFailedContextsFirst' feature I can add a flag to not save history which will fix this for you for sure.

**Comment by curdincaspar** [comment]
Yes, I saw the issue and your plans for v2. But all the other libraries and plain Selenium were never really satisfying and canopy just works :-)

I don't use the "RunFailedContextsFirst" so disabling it with a flag would work for sure.

Thanks for your fast help!

**Comment by lefthandedgoat** [comment]
This *should* fix it.  If it does not please let me know.

https://www.nuget.org/packages/canopy/1.5.2
