### ISSUE TITLE
NullReferenceException from Canopy

### ISSUE THREAD

**Issue by haf** [lefthandedgoat/canopy#404]
https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L192

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at canopy.core.suggestOtherSelectors$cont@192(String cssSelector, Unit unitVar) in C:\projects\canopy\src\canopy\canopy.fs:line 192
   at canopy.core.findByFunction[a,b,c](String cssSelector, a timeout, FSharpFunc`2 waitFunc, b searchContext, Boolean reliable) in C:\projects\canopy\src\canopy\canopy.fs:line 273
   at canopy.core.unreliableElements(String cssSelector) in C:\projects\canopy\src\canopy\canopy.fs:line 307
   at canopy.core.someElement(String cssSelector) in C:\projects\canopy\src\canopy\canopy.fs:line 333
   at EndToEndTests.Program.tests@25-1.Invoke(Unit unitVar0) in C:\dev\tradera\EndToEndTests\Program.fs:line 26
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
```

Repro:

```fsharp
        ftestCase "create a new draft" <| fun () ->
            start firefox
            url "https://tradera.com"
            someElement "button[aria-label='Meny']" |> Option.iter click
            click "a[aria-label='Skapa annons']"
```

**Comment by lefthandedgoat** [comment]
Thanks!  I will get this fixed for you on Friday.

**Comment by haf** [comment]
No rush =). Thanks for the awesome library.

**Comment by lefthandedgoat** [comment]
I wasn't able to reproduce this, but given then stacktrace I put fixes in for the two places that may have a null ref.  You can download the latest package here:

https://www.nuget.org/packages/canopy/1.6.3

Thanks haf!
