### ISSUE TITLE
Selectors don't warn about missing browser instance.

### ISSUE THREAD

**Issue by haf** [lefthandedgoat/canopy#405]
If you forget to start the browser you get a strange error message from a selector:

```
canopy.types+CanopyElementNotFoundException: can't find element button[aria-label='Meny']
   at canopy.core.findByFunction[a,b,c](String cssSelector, a timeout, FSharpFunc`2 waitFunc, b searchContext, Boolean reliable) in C:\projects\canopy\src\canopy\canopy.fs:line 274
   at canopy.core.unreliableElements(String cssSelector) in C:\projects\canopy\src\canopy\canopy.fs:line 307
   at canopy.core.someElement(String cssSelector) in C:\projects\canopy\src\canopy\canopy.fs:line 333
   at EndToEndTests.Program.tests@24-1.Invoke(Unit unitVar0) in C:\dev\tradera\EndToEndTests\Program.fs:line 25
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)

```

**Comment by lefthandedgoat** [comment]
I can add some checking for this.  Thanks for the feedback!

**Comment by lefthandedgoat** [comment]
New changes make the error message read like this

```
Can't perform the action because the browser instance is null.  `start chrome` to start a new browser.
Url: no browser = no url
Exception details:
canopy.types+CanopyNoBrowserException: Can't perform the action because the browser instance is null.  `start chrome` to start a new browser.
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f) in C:\projects\canopy\src\canopy\wait.fs:line 30
   at canopy.wait.wait(Double timeout, FSharpFunc`2 f) in C:\projects\canopy\src\canopy\wait.fs:line 35
   at canopy.core.click[a](a item) in C:\projects\canopy\src\canopy\canopy.fs:line 671
   at main.clo@74-13.Invoke(Unit _arg6) in C:\projects\canopy\tests\basictests\Program.fs:line 76
   at canopy.runner.testResult@161.Invoke(Unit x) in C:\projects\canopy\src\canopy\runner.fs:line 161
   at canopy.runner.tryTest[a,b](a test, b suite, FSharpFunc`2 func) in C:\projects\canopy\src\canopy\runner.fs:line 134
```

**Comment by lefthandedgoat** [comment]
You can download the latest package with improved error messages here:

https://www.nuget.org/packages/canopy/1.6.3

Thanks haf!
