### ISSUE TITLE
rootNode is null

### ISSUE THREAD

**Issue by haf** [lefthandedgoat/canopy#409]
```
System.InvalidOperationException: TypeError: rootNode is null
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()
   at canopy.core.takeScreenshot(String directory, String filename)
   at canopy.core.screenshot(String directory, String filename)
   at EndToEndTests.ExpectoIndirection.insideBrowser@251.Invoke(a args)
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
```

Driver: Firefox, WIndows 10 x64.

**Comment by suryanaresh** [comment]
Hello,
Even I'm facing this when I'm opening a new tab and performs actions in other URL with Firefox and Protractor.

Can someone help me on this?

Regards,
Naresh Surya
