### ISSUE TITLE
Embedding canopy fails in configuration.fs

### ISSUE THREAD

**Issue by TheGoddessInari** [lefthandedgoat/canopy#442]
If you embed canopy into the resulting assembly (such as with Fody.Costura), it fails on line 7 of configuration.fs, when it takes the reference assembly location.

This fairly well violates the principle of least surprise, as you'd expect canopy to be embeddable and only need two executables (the application executable and the webdriver).

**Comment by lefthandedgoat** [comment]
Fails in what way?  Fails to embed?

**Comment by TheGoddessInari** [comment]
`The type initializer for '<StartupCode$canopy>.$canopy.configuration' threw an exception. ---> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at <StartupCode$canopy>.$canopy.configuration..cctor() in C:\projects\canopy\src\canopy\configuration.fs:line 7
   --- End of inner exception stack trace ---
   at canopy.configuration.set_hideCommandPromptWindow(Boolean value)
   at <StartupCode$coursera-archiver>.$Program..cctor()
   --- End of inner exception stack trace ---
   at Program.main(String[] args)`

At runtime. It raises an exception when embedded.
