### ISSUE TITLE
Firefox 63 crashes

### ISSUE THREAD

**Issue by kevinmcfarlane** [lefthandedgoat/canopy#453]
I'm somewhat out-of-date on Canopy (1.5.0). F# Core 3.0.2. Selenium Firefox Web Driver 0.19.1. Selenium Web Driver 3.9.1.

Firefox launches and then immediately crashes at `start firefox` statement.

Unhandled Exception: System.InvalidOperationException: newSession
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service)
   at canopy.core.start(BrowserStartMode b) in C:\projects\canopy\src\canopy\canopy.fs:line 875

This was working in Firefox 62.0.3. It is also working in latest Chrome using Selemium Chrome Web Driver 2.35.0.

Ultimately, I will upgrade everything but thought I'd check here first.

**Comment by lefthandedgoat** [comment]
With chrome, when things work well for a while then stop working with a new browser, 9 time out of 10, simply updating to the latest chrome driver fixes it.  Each version of chrome driver is usually targeted for 4 version of chrome.  It generally works longer than that thought.

If the same thing applies for firefox, I would say updating geckodriver first is your best bet.  Next I would update selenium.  I doubt you need to update canopy, but you may want to.

FYI, 2.0 has some breaking changes, here is an upgrade guide: https://lefthandedgoat.github.io/canopy/upgrade1to2.html

You may want to just upgrade to 1.6.3, it shouldnt have any breaking changes from 1.5

https://www.nuget.org/packages/canopy/1.6.3

Hope this helps!

**Comment by kevinmcfarlane** [comment]
Thanks for your quick reply Chris. I just updated the Gecko driver and it's now working. 👍
